version: '3'
services:
  my_client:
    image: mattiskj/hgop:ui${GIT_COMMIT}
    ports:
    - '4000:4000'
    depends_on:
      - my_api
    environment:
      PORT: 4000
      API_PORT: 3000
      API_URL: ${API_URL}
  my_api:
    image: mattiskj/hgop:${GIT_COMMIT}
    ports:
    - '3000:3000'
    depends_on:
    - my_database_container
    environment:
      PORT: 3000
      POSTGRES_HOST: 'my_database_container'
      POSTGRES_DB: 'game_database'
      POSTGRES_USER: 'my_user'
      POSTGRES_PASSWORD: 'my_password'
  my_database_container:
    image: postgres
    environment:
      POSTGRES_DB: 'game_database'
      POSTGRES_USER: 'my_user'
      POSTGRES_PASSWORD: 'my_password'
  my_datadog_container:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=091b1abb9d0d87a3f6d1a8bb71496cd4
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_TAGS=env:${ENVIRONMENT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro



